config/routes.rb
MiPrimeraWebRuby::Application.routes.draw do
  resources :admissions

  resources(:cases, {:only => [:show, :index]})
  get "cases/show"

  get "cases/index"

end

app/models/admission.rb
class Admission < ActiveRecord::Base
  attr_accessible :case_id, :date, :status
  belongs_to :case
end

app/models/case.rb
class Case < ActiveRecord::Base
  attr_accessible :birthdate, :name
  has_many :admissions

  def age
    Date.today.year - birthdate.year
  end


end

app/controllers/admissions_controller.rb
class AdmissionsController < ApplicationController
  # GET /admissions
  # GET /admissions.json
  def index
    @admissions = Admission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admissions }
    end
  end

  # GET /admissions/1
  # GET /admissions/1.json
  def show
    @admission = Admission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admission }
    end
  end

  # GET /admissions/new
  # GET /admissions/new.json
  def new
    @admission = Admission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admission }
    end
  end

  # GET /admissions/1/edit
  def edit
    @admission = Admission.find(params[:id])
  end

  # POST /admissions
  # POST /admissions.json
  def create
    @admission = Admission.new(params[:admission])

    respond_to do |format|
      if @admission.save
        format.html { redirect_to @admission, notice: 'Admission was successfully created.' }
        format.json { render json: @admission, status: :created, location: @admission }
      else
        format.html { render action: "new" }
        format.json { render json: @admission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admissions/1
  # PUT /admissions/1.json
  def update
    @admission = Admission.find(params[:id])

    respond_to do |format|
      if @admission.update_attributes(params[:admission])
        format.html { redirect_to @admission, notice: 'Admission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admissions/1
  # DELETE /admissions/1.json
  def destroy
    @admission = Admission.find(params[:id])
    @admission.destroy

    respond_to do |format|
      format.html { redirect_to admissions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    @cases = Case.all
  end

  def show
    @id = params[:id]
    @case = Case.find(@id)
    @admi = @case.admissions.where( :status => "closed")
  end
end

app/helpers/admissions_helper.rb
module AdmissionsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
 # son metodos para ayudar a las vistas. Este metodo pasa el nombre a mayusculas
 def case_name( case_aux )
    link_to case_aux.name.to_s.upcase  , case_aux
 end


end

app/views/admissions/_form.html.erb
<%= form_for(@admission) do |f| %>
  <% if @admission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admission.errors.count, "error") %> prohibited this admission from being saved:</h2>

      <ul>
      <% @admission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :case_id %><br />
    <%= f.number_field :case_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admissions/edit.html.erb
<h1>Editing admission</h1>

<%= render 'form' %>

<%= link_to 'Show', @admission %> |
<%= link_to 'Back', admissions_path %>

app/views/admissions/index.html.erb
<h1>Listing admissions</h1>

<table>
  <tr>
    <th>Case</th>
    <th>Status</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admissions.each do |admission| %>
  <tr>
    <td><%= admission.case_id %></td>
    <td><%= admission.status %></td>
    <td><%= admission.date %></td>
    <%# el link_to es para poner un enlace en la web hacia la pantalla de case %>
    <td><%= case_name(admission.case)%></td>
    <td><%#link_to admission.case.name, admission.case %></td>
    <td><%= link_to 'Show', admission %></td>
    <td><%= link_to 'Edit', edit_admission_path(admission) %></td>
    <td><%= link_to 'Destroy', admission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admission', new_admission_path %>

app/views/admissions/new.html.erb
<h1>New admission</h1>

<%= render 'form' %>

<%= link_to 'Back', admissions_path %>

app/views/admissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Case:</b>
  <%= @admission.case_id %>
</p>

<p>
  <b>Status:</b>
  <%= @admission.status %>
</p>

<p>
  <b>Date:</b>
  <%= @admission.date %>
</p>


<%= link_to 'Edit', edit_admission_path(@admission) %> |
<%= link_to 'Back', admissions_path %>

app/views/cases/index.html.erb
<h1>Cases#index</h1>
<ul>
  <% @cases.each do |a_case| %>
  <li>
    <p>
      <%= a_case.name %>
    </p>
    <p>
      <%= a_case.birthdate %>
    </p>
    <p>
      <%= a_case.age %>  PM2222
    </p>
  </li>
      <% end %>

</ul>

app/views/cases/show.html.erb
<h1>Cases#show</h1>
<p>El id es <%=case_name(@case) %></p>
<ul>
  <% @admi.each do |a_admi| %>
  <li>
    <p>
      <%= a_admi.id %>
    </p>
    <p>
      <%= a_admi.status %>
    </p>
    <p>
      <%= a_admi.date %>  PM2222
    </p>
  </li>
      <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiPrimeraWebRuby</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>